version: '3'
services:
    mongo:
        image: 'mongo'
        container_name: 'mongo'
        restart: 'always'
        volumes:
        - 'mongo_data:/data/db'
        ports:
            - '27017:27017'
    redis:
        image: 'redis'
        container_name: 'redis'
        restart: 'always'
        ports:
            - '6379:6379'
    cve-search:
        image: 'cve-search:latest'
        container_name: 'cve-search'
        ports:
            - '5000:5000'
        links:
            - mongo
            - redis
volumes:
    mongo_data: